-- ============================================
-- SISTEM ALAMAT USER (SEPERTI SHOPEE)
-- ============================================

-- Table: user_addresses
CREATE TABLE IF NOT EXISTS user_addresses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_phone TEXT NOT NULL, -- Menggunakan phone sebagai identifier user
  label TEXT NOT NULL, -- 'Rumah', 'Kantor', 'Kos', dll
  recipient_name TEXT NOT NULL,
  recipient_phone TEXT NOT NULL,
  full_address TEXT NOT NULL,
  detail_address TEXT, -- Patokan, warna rumah, dll
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  maps_link TEXT,
  is_primary BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index untuk performa
CREATE INDEX IF NOT EXISTS idx_user_addresses_phone ON user_addresses(user_phone);
CREATE INDEX IF NOT EXISTS idx_user_addresses_primary ON user_addresses(user_phone, is_primary);

-- Trigger untuk update timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_user_addresses_updated_at 
  BEFORE UPDATE ON user_addresses 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Trigger untuk memastikan hanya 1 alamat primary per user
CREATE OR REPLACE FUNCTION ensure_single_primary_address()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.is_primary = TRUE THEN
    -- Set semua alamat user lain jadi non-primary
    UPDATE user_addresses 
    SET is_primary = FALSE 
    WHERE user_phone = NEW.user_phone 
      AND id != NEW.id;
  END IF;
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER ensure_single_primary_address_trigger
  BEFORE INSERT OR UPDATE ON user_addresses
  FOR EACH ROW
  EXECUTE FUNCTION ensure_single_primary_address();

-- Update table orders untuk support address_id
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_id BIGINT REFERENCES user_addresses(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_latitude DECIMAL(10, 8);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_longitude DECIMAL(11, 8);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_maps_link TEXT;

-- Sample data (optional)
-- INSERT INTO user_addresses (user_phone, label, recipient_name, recipient_phone, full_address, detail_address, latitude, longitude, is_primary) VALUES
-- ('6285263965031', 'Rumah', 'John Doe', '6285263965031', 'Jl. Contoh No. 123, Padang Pariaman', 'Rumah cat hijau, pagar putih', -0.6050000, 100.2150000, TRUE),
-- ('6285263965031', 'Kantor', 'John Doe', '6285263965031', 'Jl. Kerja No. 456, Padang', 'Gedung lantai 3', -0.9471, 100.4172, FALSE);

-- Query helper functions (untuk reference)
-- 1. Get all addresses for a user
-- SELECT * FROM user_addresses WHERE user_phone = '6285263965031' ORDER BY is_primary DESC, created_at DESC;

-- 2. Get primary address
-- SELECT * FROM user_addresses WHERE user_phone = '6285263965031' AND is_primary = TRUE LIMIT 1;

-- 3. Set address as primary
-- UPDATE user_addresses SET is_primary = TRUE WHERE id = 1;

-- 4. Delete address
-- DELETE FROM user_addresses WHERE id = 1;

-- 5. Count user addresses
-- SELECT COUNT(*) FROM user_addresses WHERE user_phone = '6285263965031';
