-- Table: push_subscriptions
-- Stores Web Push API subscriptions for both admin and user notifications.
-- Each row ties a browser's push subscription to a user_id and role.

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  subscription TEXT NOT NULL,           -- JSON stringified PushSubscription
  role TEXT NOT NULL DEFAULT 'user',    -- 'admin' or 'user'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookups by user_id
CREATE INDEX IF NOT EXISTS idx_push_subs_user_id ON push_subscriptions(user_id);

-- Index for fast lookups by role (e.g. finding all admin subscriptions)
CREATE INDEX IF NOT EXISTS idx_push_subs_role ON push_subscriptions(role);

-- Unique constraint to prevent duplicate subscriptions
CREATE UNIQUE INDEX IF NOT EXISTS idx_push_subs_unique ON push_subscriptions(user_id, endpoint);

-- RLS Policies
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to insert their own subscriptions
CREATE POLICY "Users can insert own subscriptions" ON push_subscriptions
  FOR INSERT TO authenticated
  WITH CHECK (true);

-- Allow authenticated users to update their own subscriptions
CREATE POLICY "Users can update own subscriptions" ON push_subscriptions
  FOR UPDATE TO authenticated
  USING (true);

-- Allow authenticated users to read their own subscriptions
CREATE POLICY "Users can read own subscriptions" ON push_subscriptions
  FOR SELECT TO authenticated
  USING (true);

-- Allow service role to do everything (for the API routes)
CREATE POLICY "Service role full access" ON push_subscriptions
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);
