-- Table: products
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  "desc" TEXT,
  price INTEGER NOT NULL,
  category TEXT NOT NULL,
  img TEXT NOT NULL,
  sold_count INTEGER DEFAULT 0,
  stock INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: reviews
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  text TEXT NOT NULL,
  rating INTEGER NOT NULL,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: orders
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  delivery_method TEXT NOT NULL,
  customer_address TEXT,
  payment_method TEXT NOT NULL,
  pickup_date DATE,
  subtotal INTEGER NOT NULL,
  shipping_cost INTEGER,
  shipping_discount INTEGER,
  grand_total INTEGER NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: order_items
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  qty INTEGER NOT NULL,
  price INTEGER NOT NULL
);

-- Insert Initial Products Data
INSERT INTO products (id, name, "desc", price, category, img) VALUES
(1, 'Nugget Ayam', 'Nugget ayam crispy premium, 500gr. Cocok untuk camilan keluarga.', 32000, 'frozen', '/assets/images/nugget.png'),
(2, 'Sosis Sapi', 'Sosis sapi berkualitas, 300gr. Praktis untuk bekal dan masakan.', 28000, 'frozen', '/assets/images/sosis.png'),
(3, 'Bakso Sapi', 'Bakso sapi kenyal isi 25 butir. Bahan pilihan, tanpa pengawet.', 35000, 'frozen', '/assets/images/bakso.png'),
(4, 'Dimsum Ayam', 'Dimsum ayam isi udang, 10 pcs. Tinggal kukus, siap saji!', 25000, 'frozen', '/assets/images/nugget.png'),
(5, 'Kentang Goreng', 'Kentang goreng crinkle cut 1kg. Renyah dan lezat.', 42000, 'frozen', '/assets/images/sosis.png'),
(6, 'Otak-otak', 'Otak-otak ikan tenggiri, 10 pcs. Bumbu rempah khas.', 22000, 'frozen', '/assets/images/bakso.png'),
(7, 'Buku Tulis', 'Buku tulis 58 lembar, sampul tebal. Tersedia bergaris dan kotak.', 5000, 'atk', '/assets/images/buku-tulis.png'),
(8, 'Pulpen Pilot', 'Pulpen Pilot 0.5mm, tinta smooth. Nyaman digunakan menulis lama.', 8000, 'atk', '/assets/images/pulpen.png'),
(9, 'Kertas HVS A4', 'Kertas HVS A4 70gsm, 500 lembar/rim. Untuk print dan fotokopi.', 48000, 'atk', '/assets/images/buku-tulis.png'),
(10, 'Pensil 2B', 'Pensil 2B Faber Castell, 12 pcs/box. Cocok untuk ujian.', 24000, 'atk', '/assets/images/pulpen.png'),
(11, 'Map Plastik', 'Map plastik kancing F4, tebal dan tahan lama. Aneka warna.', 3500, 'atk', '/assets/images/buku-tulis.png'),
(12, 'Spidol Snowman', 'Spidol whiteboard Snowman, 12 warna. Mudah dihapus.', 36000, 'atk', '/assets/images/pulpen.png'),
(13, 'Tisu Wajah', 'Tisu wajah lembut, 250 sheets.', 12000, 'other', '/assets/images/buku-tulis.png'),
(14, 'Botol Minum', 'Botol minum plastik BPA Free 1L.', 25000, 'other', '/assets/images/pulpen.png');

-- Table: banners
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  subtitle TEXT,
  description TEXT,
  image_url TEXT NOT NULL,
  bg_color TEXT DEFAULT '#111827',
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  buttons JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default hero banners (hanya jika tabel kosong)
INSERT INTO banners (title, subtitle, description, image_url, bg_color, is_active, sort_order, buttons)
SELECT * FROM (VALUES
  (
    'HIJRAH TOKO',
    'Satu Pintu Solusi Anda',
    'Menghadirkan kenyamanan belanja Frozen Food premium dan kelengkapan ATK dalam satu genggaman modern.',
    '/assets/images/hero-toko.jpeg',
    'linear-gradient(to right, rgba(0,0,0,0.88) 0%, rgba(0,0,0,0.6) 45%, rgba(0,0,0,0.15) 100%)',
    true,
    0,
    '[{"label":"Jelajahi Produk","url":"#kategori","style":"primary"},{"label":"Hubungi Admin","url":"https://wa.me/6285263965031","style":"outline"}]'::jsonb
  ),
  (
    'Belanja Lebih Cepat & Praktis',
    'Aplikasi Mobile Ready',
    'Install aplikasi Hijrah Toko di HP Anda. Akses katalog, keranjang, dan tracking pesanan dalam satu sentuhan.',
    '/assets/images/hero-aplikasi.jpeg',
    'linear-gradient(to right, rgba(10,10,10,0.97) 0%, rgba(10,10,10,0.85) 40%, rgba(10,10,10,0.4) 70%, rgba(10,10,10,0.1) 100%)',
    true,
    1,
    '[{"label":"Install Aplikasi","url":"#","style":"primary"},{"label":"Lihat Produk","url":"#produk","style":"outline"}]'::jsonb
  ),
  (
    'Kenalan dengan NURA',
    'Powered by AI',
    'Chef AI assistant yang siap membantu kamu memasak frozen food dengan resep, tips, dan trik yang praktis.',
    '/assets/images/nura.png',
    '#111827',
    true,
    2,
    '[{"label":"Chat dengan Nura","url":"/chef","style":"primary"},{"label":"Lihat Produk","url":"#produk","style":"outline"}]'::jsonb
  )
) AS v(title, subtitle, description, image_url, bg_color, is_active, sort_order, buttons)
WHERE NOT EXISTS (SELECT 1 FROM banners LIMIT 1);

-- Table: push_subscriptions
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL,
  endpoint TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  subscription JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
